services:
  - type: web
    name: universal-job-scraper-api
    env: node
    plan: free
    buildCommand: |
      apt-get update
      apt-get install -y chromium-browser
      npm install
    startCommand: npm start
    envVars:
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: true
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /usr/bin/chromium-browser
